AY2122S2-CS2113T-T10-1/tp

- docs/AboutUs.md
> Add my name lmao

- src/main/java/seedu/duke/data/Session.java
Add Session class
Add attributes to Session class
> Branch session

- src/main/java/seedu/duke/data/Session.java
Comment out continuous integration check violating lines
> Fix continuous integration violating lines

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/ui/TextUI.java
Includes functions to print to and read from the user interface.
Includes functions to print welcome and farewell messages to the user interface.
Includes a function that prints a divider line to the user interface (currently private).
Fixes #28
> Implement TextUI

- src/main/java/seedu/duke/data/Profile.java
> Branch profile

- src/main/java/seedu/duke/ui/Message.java
Message is an abstract class that contains hardcoded Strings such as error codes and such. Please add any Strings you want to use to it as constants.
Fixes #31
> Add Message class

- src/main/java/seedu/duke/exceptions/InvalidDataException.java
Thrown when issues related to invalid variables (such as null variables, variables out of bounds etc) are encountered. Not for command formatting issues.
> Add InvalidDataException class

- src/main/java/seedu/duke/exceptions/InvalidFormatException.java
Throw this exception when encountering format-related errors such as
invalid input.
Includes documentation on each constructor.
Fixes #48
> Add InvalidFormatException class

- src/main/java/seedu/duke/command/SessionCreateCommand.java
> Command session create

- src/main/java/seedu/duke/data/ActivityCost.java
Contains three constructors:
ActivityCost(int activityId, double cost)
ActivityCost(int activityId) // sets cost to 0
ActivityCost() // sets activityId to -1 and cost to 0.
The first two throw exceptions if a negative activityId or cost is supplied.
Includes getters and setters for activityId and cost.
Fixes #26
> Add ActivityCost class

- src/main/java/seedu/duke/command/ActivityCreateCommand.java
Implemented the constructor and the attributes of the ActivityCreateCommand class.
Fixes #54
> Branch activity create command

- src/main/java/seedu/duke/data/ActivityCost.java
- src/main/java/seedu/duke/data/Profile.java
- src/main/java/seedu/duke/exceptions/InvalidDataException.java
- src/main/java/seedu/duke/exceptions/InvalidFormatException.java
- src/main/java/seedu/duke/ui/Message.java
- src/main/java/seedu/duke/ui/TextUI.java
ActivityCost no longer checks for invalid input or throws exceptions.
The Parser should handle invalid input
Fixes #57
> Remove error checking from ActivityCost

- src/main/java/seedu/duke/command/SessionCreateCommand.java
- src/main/java/seedu/duke/command/SessionDeleteCommand.java
> Command session delete

- src/main/java/seedu/duke/parser/Parser.java
- src/main/java/seedu/duke/ui/Message.java
Add command parsing methods to Parser class
Fixes #65
> Branch parser

- src/main/java/seedu/duke/data/ActivityCost.java
- src/main/java/seedu/duke/data/Person.java
- src/main/java/seedu/duke/data/Profile.java
- src/main/java/seedu/duke/exceptions/InvalidDataException.java
- src/main/java/seedu/duke/exceptions/InvalidFormatException.java
- src/main/java/seedu/duke/ui/Message.java
- src/main/java/seedu/duke/ui/TextUI.java
Contains the name, totalCost and a list of activityCosts.
Getters included but no setters.
Use addActivityCost(int activityId, double cost) to add activityCosts to the Person object after instantiating it.
Fixes #54
> Add Person class

- src/main/java/seedu/duke/command/SessionSummaryCommand.java
Add class member attributes and constructors
Add JavaDoc comments to the class and methods
> Add SessionSummaryCommand class

- src/main/java/seedu/duke/data/Activity.java
Added the constructors and the attributes for Activity Class.
Fixes #74
> Branch activity

- src/main/java/seedu/duke/command/ActivityListCommand.java
Add class attributes and constructor
Fix #76
> Initialisation of ActivityListCommand class

- src/main/java/seedu/duke/command/ActivityViewCommand.java
Add class attributes and constructor
Fix #79
> Initialisation of ActivityViewCommand class

- src/main/java/seedu/duke/command/ExitCommand.java
Added ExitCommand class
Added command_text and command_format attributes
Added javadocs
Fixes #80
> Command exit

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/Command.java
- src/main/java/seedu/duke/command/ExitCommand.java
- src/main/java/seedu/duke/parser/Parser.java
- text-ui-test/input.txt
> Integration for ExitCommand

- src/main/java/seedu/duke/data/Manager.java
Added manager class
Added attributes, constructor and getter functions
Fixes #86
> Branch manager

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/ActivityCreateCommand.java
- src/main/java/seedu/duke/command/ActivityListCommand.java
- src/main/java/seedu/duke/command/ActivityViewCommand.java
- src/main/java/seedu/duke/command/Command.java
- src/main/java/seedu/duke/command/ExitCommand.java
- src/main/java/seedu/duke/command/InvalidCommand.java
- src/main/java/seedu/duke/command/SessionCreateCommand.java
- src/main/java/seedu/duke/command/SessionDeleteCommand.java
- src/main/java/seedu/duke/command/SessionSummaryCommand.java
> integrate Manager class into existing Command classes

- src/main/java/seedu/duke/command/HelpCommand.java
- src/main/java/seedu/duke/parser/Parser.java
- src/main/java/seedu/duke/ui/Message.java
- src/main/java/seedu/duke/ui/TextUI.java
Add HelpCommand class
Add member attributes and run() method functionality
Add JavaDocs comments
Integrate HelpCommand to Parser class
Fixes #67
> Add HelpCommand class

- src/main/java/seedu/duke/command/SessionListCommand.java
- src/main/java/seedu/duke/parser/Parser.java
> added attributes for session list

- src/main/java/seedu/duke/command/ActivityDeleteCommand.java
Implemented the attributes and the constructor for ActivityDeleteCommand class
Fixes #106
> Branch activity delete command

- src/main/java/seedu/duke/data/ActivityCost.java
- src/main/java/seedu/duke/data/Person.java
ActivityCost now supports these constructors:
public ActivityCost(int activityId, double costPaid, double costOwed)
public ActivityCost(int activityId)
public ActivityCost() 
getters and setters for cost have been removed.
getters and setters for costPaid and costOwed have been added.
Person class' addActivityCost method has been replaced with
public void addActivityCost(int activityId, double costPaid, double costOwed)
Person class now has these three methods:
getTotalCostOwed() : returns the sum of all costOweds associated with this Person.
getTotalCostPaid() : returns the sum of all costPaids associated with this Person.
getTotalCost() : returns the sum of all costPaids - sum of all costOweds associated with this Person. This represents the amount of money everyone else owes to this …
> add costPaid and costOwed to activityCost and modify Person to support these

- src/main/java/seedu/duke/data/Session.java
- src/main/java/seedu/duke/ui/Message.java
Add new attribute to Session class
Add supporting getter methods
Add other supporting methods
Add JavaDocs comments for newly added comments
Rectify previously committed comments
Fixes #110
> Integrate Person class into Session class

- src/main/java/seedu/splitlah/data/Person.java
- src/main/java/seedu/splitlah/ui/Message.java
This method accepts an int representing the activityId. It returns the cost owed by this Person for this Activity as a double.
This method throws InvalidDataException if the Person has no Activities, or if the activityId is not found in the Person's list of Activities.
Fixes #116
> Add getActivityCostId method to Person

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/ui/Message.java
> initial set up for run function in SessionCreateCommand

- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/ui/Message.java
Add getters and remover methods for Activity objects into Session class.
Add basic constructor to Session class.
Add summary string builder methods for personList and activityList in Session class.
Add toString() method to summarise a Session object.
Add JavaDocs comments to all new methods.
Fixes #111 
Fixes #69
> Integrate Activity class into Session class

- src/main/java/seedu/splitlah/data/ActivityCost.java
- src/main/java/seedu/splitlah/data/Person.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/main/java/seedu/splitlah/ui/TextUI.java
Person:
Added removeActivityCost(int activityId) method that removes the ActivityCost object with the corresponding activityId from this Person object.
ActivityCost:
Added equals and hashCode override methods. ActivityCost objects now check for equality using their activityIds. Two ActivityCost objects with the same ActivityId will be considered equal by the equals method.
TextUI:
Added doubleConfirm(String message) method that prints the message to the UI and asks for user confirmation.
Inputting Y/y/yes to the interface returns true.
Inputting N/n/no to the interface returns false and prints a message indicating that the user did not confirm.
Any other input prints an error message and asks the user to re-input.
Fixes #127
Fixes #128
> Add removeActivityCost and doubleConfirm methods

- src/main/java/seedu/splitlah/data/Session.java
Add code to remove ActivityCost objects from all involved Person objects with the same activityId as the Activity object to be removed.
> Rectify removeActivity() method in Session class

- src/main/java/seedu/splitlah/data/Session.java
Shift getInvolvedPersonList() method from CreateActivityCommand to Session class
Add JavaDocs comments for newly created method
> Add method to support CreateActivityCommand class

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
Completed the initial function of session creation.
Polishing to be done by end of the week with Junit test.
Fixes #132
> integration for SessionCreateCommand

- src/main/java/seedu/splitlah/util/PersonCostPair.java
Add member attributes
Add getters and setters
Add Comparator methods
Add constructor
Fixes #135
> add PersonCostPair utility class to support SessionSummaryCommand class

- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
Add prepare() method
Add supporting methods and constants
Add key functionality methods
Implement run() method
Fixes #137 
Fixes #138
> Implement key functionality of SessionSummaryCommand class

- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
> add prepare function for SessionDeleteCommand

- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
Add prepare method in ActivityCreateCommand class
Add Javadocs for all methods in ActivityCreateCommand class.
Fixes #42
> Add relevant methods and Javadoc for ActivityCreateCommand

- src/main/java/seedu/splitlah/SplitLah.java
- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/command/ActivityDeleteCommand.java
- src/main/java/seedu/splitlah/command/ActivityListCommand.java
- src/main/java/seedu/splitlah/command/ActivityViewCommand.java
- src/main/java/seedu/splitlah/command/Command.java
- src/main/java/seedu/splitlah/command/ExitCommand.java
- src/main/java/seedu/splitlah/command/HelpCommand.java
- src/main/java/seedu/splitlah/command/InvalidCommand.java
- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/command/SessionListCommand.java
- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/data/Activity.java
- src/main/java/seedu/splitlah/data/ActivityCost.java
- src/main/java/seedu/splitlah/data/Manager.java
- src/main/java/seedu/splitlah/data/Person.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/exceptions/InvalidDataException.java
- src/main/java/seedu/splitlah/exceptions/InvalidFormatException.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/main/java/seedu/splitlah/ui/TextUI.java
- src/main/java/seedu/splitlah/util/PersonCostPair.java
Sat down for team meeting to discuss overall standardisation of
JavaDocs comments and code formatting.
> Set overall standardisation for coding

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/data/Profile.java
Amend current javadocs for SessioCreateCommand, SessionDeleteCommand and Profile class to adhere to team's javadocs standardization.
> Misc javadocs

- src/main/java/seedu/splitlah/data/Activity.java
- src/main/java/seedu/splitlah/ui/Message.java
Replace getActivityDetails method with toString method
Update Javadoc for methods and constructors to follow overall standardization
Rearrange methods, constants and attributes to follow overall standardization
Fixes #147
> Update Activity class

- src/test/java/seedu/splitlah/command/SessionCreateCommandTest.java
Added Junit test file for SessionCreateCommand.
Added tests function to check if session is created if /pl argument contains duplicated names.
Fixes: #150
> junit test for SessionCreateCommand

- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
Add handling for non-positive id input to print the correct error message.
> Rectify error message for non-positive id input by user

- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/data/Profile.java
> implement run function for SessionDeleteCommand

- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
Fixed bug for activityCreateCommand class to check if costList is null before getting length of costList
Add printing of success message after successfully creating an activity
> Update activityCreateCommand class

- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
Add more details in summary string
Add more error checks to ensure proper functionality
Reorganise code for standardisation
Fixes #41
> Update SessionSummaryCommand class to make it more functional

- docs/README.md
- docs/UserGuide.md
Add UG for session delete command
Add intro for UserGuide.md
Add intro for README.md
> user guide update

- src/main/java/seedu/splitlah/command/SessionListCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/TextUI.java
> complete SessionListCommand 

- src/main/java/seedu/splitlah/ui/Message.java
- src/main/java/seedu/splitlah/ui/TextUI.java
getUserConfirmation would not ask the user to re-input if invalid input was detected, leading to an infinite loop.
Fixes this by prompting the user to re-input if invalid input is detected.
> Fix infinite loop bug in getUserConfirmation

- src/main/java/seedu/splitlah/command/ActivityListCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
> Activity list command

- src/main/java/seedu/splitlah/command/ActivityViewCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
> Activity view command

- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/command/ActivityListCommand.java
- src/main/java/seedu/splitlah/command/ActivityViewCommand.java
- src/main/java/seedu/splitlah/data/Activity.java
Update methods in Activity class to follow overall printing standardization
Update COMMAND_SUCCESS constant in ActivityCreateCommand class
Update run method in ActivityViewCommand class to follow overall printing standardization
Update run method in ActivityListCommand class to follow overall printing standardization
> Debug and fix issues for activity related classes

- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/ui/Message.java
Reorganise code layout
Add getSessionSimplifiedString() for SessionListCommand class
Add assertions to check for edge cases in Session class
Fixes #10 
Fixes #178
> Add support for SessionListCommand class in Session class

- src/main/java/seedu/splitlah/command/InvalidCommand.java
- src/main/java/seedu/splitlah/data/ActivityCost.java
- src/main/java/seedu/splitlah/data/Person.java
- src/main/java/seedu/splitlah/exceptions/InvalidDataException.java
- src/main/java/seedu/splitlah/exceptions/InvalidFormatException.java
- src/main/java/seedu/splitlah/ui/TextUI.java
Aligns @param descriptions in several methods. No code changes
> Update JavaDocs formatting

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/command/SessionListCommand.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/ui/TextUI.java
Amend existing javadocs for Session related commands
Change printing style for Session list command
> clean up javadocs for Session related commands

- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
Update formatting of output message
Convert temporary error checks to assertion statements
Add JavaDocs comments to all methods
Fixes #101 
Fixes #139
> Clean up SessionSummaryCommand class and add JavaDocs comments

- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/test/java/seedu/splitlah/command/SessionCreateCommandTest.java
Add error message in Message class
Rearrange case blocks in getCommand() method
Update JUnit tests to use updated date parsing format
> Update date parsing format in Parser class

- docs/UserGuide.md
- src/test/java/seedu/splitlah/data/ActivityCostTest.java
Tests activityCost getter methods.
Fixes #188
> Add activityCost getter JUnit tests

- docs/UserGuide.md
- docs/_config.yml
Adds information to the User Guide for v1.0.
> Add Intro, QuickStart, FAQ, Command Summary, Table of Contents to UG

- src/main/java/seedu/splitlah/parser/Parser.java
> Furnish JavaDoc comments to Parser class

- src/test/java/seedu/splitlah/command/SessionCreateCommandTest.java
- src/test/java/seedu/splitlah/command/SessionDeleteCommandTest.java
> junit test for SessionDeleteCommand

- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/command/ActivityDeleteCommand.java
- src/main/java/seedu/splitlah/command/ActivityListCommand.java
- src/main/java/seedu/splitlah/command/ActivityViewCommand.java
- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
Fix issue where there can be multiple irrelevant delimiters
Fix issue where there can be tokens without accompanying delimiters
Update check to ensure 2 decimal places for costs input
Fixes #215
> Add error checks to fix bugs found

- src/test/java/seedu/splitlah/parser/ParserTest.java
> Add more JUnit tests to Parser class

- src/main/java/seedu/splitlah/SplitLah.java
- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/data/Manager.java
- src/main/java/seedu/splitlah/ui/Message.java
set up logger functions for main
update existing logger functions for SessionCreateCommand and SessionDeleteCommand
> Branch logger

- src/test/java/seedu/splitlah/parser/ParserTest.java
Current progress of parse methods up to this PR: 10/12 public parse methods completed.
> Add more JUnit tests for Parser class parse methods

- src/main/java/seedu/splitlah/data/Group.java
- src/main/java/seedu/splitlah/ui/Message.java
> Set up Group class

- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
> Add logging statements to SessionSummaryCommand class

- src/main/java/seedu/splitlah/command/ActivityListCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
> Add assert and logging in ActivityListCommand class

- src/main/java/seedu/splitlah/command/InvalidCommand.java
- src/main/java/seedu/splitlah/data/ActivityCost.java
- src/main/java/seedu/splitlah/data/Manager.java
- src/main/java/seedu/splitlah/ui/Message.java
InvalidCommand now checks if the Manager supplied to it exists.
ActivityCost logs the type of ActivityCost created (based on the
parameters supplied) when creating one.
Fixes #261 and #260
> Add logging and assertions

- src/main/java/seedu/splitlah/data/ActivityCost.java
> Change logging level in ActivityCost

- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/ui/Message.java
> Add supporting functions for Group class in Profile Class

- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/test/java/seedu/splitlah/command/ActivityCreateCommandTest.java
Remove redundant tests
Add new tests
Edit the name of the constants
> Update Junit tests for Activity Create Command

- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/ui/Message.java
Add parseGroupId() method to Parser class to allow for creation of GroupCommand classes.
Fixes #265
> Update JavaDocs and add support for Group Class in Parser class

- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/test/java/seedu/splitlah/command/SessionDeleteCommandTest.java
> revamp SessionDeleteCommand Class

- src/main/java/seedu/splitlah/command/ActivityDeleteCommand.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/test/java/seedu/splitlah/command/ActivityDeleteCommandTest.java
Remove user confirmation
Add additional tests for activity delete command
> Update Activity Delete Command

- build.gradle
- src/main/java/seedu/splitlah/data/Session.java
- text-ui-test/EXPECTED.TXT
Add Group object as member attribute.
Add constructor and getter methods to support Group class.
Update summary string methods to include support for Group class.
Fixes #266 
Fixes #282
> Integrate Group class into Session class

- src/main/java/seedu/splitlah/command/GroupDeleteCommand.java
- src/main/java/seedu/splitlah/data/Group.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/parser/Parser.java
> Setup GroupDeleteCommand class

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/data/Person.java
- src/main/java/seedu/splitlah/data/PersonList.java
- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/ui/Message.java
- text-ui-test/EXPECTED.TXT
> Group integration with SessionCreateCommand

- src/main/java/seedu/splitlah/command/GroupViewCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/parser/ParserUtils.java
- src/main/java/seedu/splitlah/ui/Message.java
Add necessary methods, attributes, constants to Group View Command
Fix #236
> Add Group View Command

- src/main/java/seedu/splitlah/ui/TextUI.java
The program should no longer ask the user for confirmation.
Fixes #302
> Remove user confirmation method

- src/main/java/seedu/splitlah/command/GroupCreateCommand.java
- src/main/java/seedu/splitlah/data/Group.java
- src/main/java/seedu/splitlah/data/PersonList.java
> Integrate PersonList with Group related commands

- .gitignore
- src/main/java/seedu/splitlah/SplitLah.java
- src/main/java/seedu/splitlah/command/ActivityCreateCommand.java
- src/main/java/seedu/splitlah/command/ActivityDeleteCommand.java
- src/main/java/seedu/splitlah/command/GroupCreateCommand.java
- src/main/java/seedu/splitlah/command/GroupDeleteCommand.java
- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/data/Activity.java
- src/main/java/seedu/splitlah/data/ActivityCost.java
- src/main/java/seedu/splitlah/data/Group.java
- src/main/java/seedu/splitlah/data/Manager.java
- src/main/java/seedu/splitlah/data/Name.java
- src/main/java/seedu/splitlah/data/Person.java
- src/main/java/seedu/splitlah/data/PersonList.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/storage/Storage.java
- src/main/java/seedu/splitlah/ui/Message.java
- text-ui-test/EXPECTED.TXT
Set up storage class
Integrate with existing command classes to use storage class
Update all data classes to `extends Serializable` for file storage
Fixes #226
> Set up storage class

- src/main/java/seedu/splitlah/data/Name.java
- src/main/java/seedu/splitlah/data/Person.java
- src/test/java/seedu/splitlah/data/NameTest.java
Person now stores a Name object instead of a String to make validating the name easier.
Person does not currently throw an InvalidDataException when an invalid String is supplied to construct a Person object, but it will in the future once other code has been updated to use try and catch blocks.
> Integrate Name into Person

- src/main/java/seedu/splitlah/command/SessionListCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/parser/ParserUtils.java
- src/main/java/seedu/splitlah/parser/commandparser/SessionListCommandParser.java
- src/main/java/seedu/splitlah/ui/Message.java
> Integrate SessionListCommand class to use new Parser classes

- src/main/java/seedu/splitlah/SplitLah.java
- src/main/java/seedu/splitlah/ui/TableFormatter.java
- src/main/java/seedu/splitlah/ui/TableFormatterRow.java
Adds a TableFormatter and a helper class TableFormatterRow to create and print cleanly formatted tables.
> Add TableFormatter class

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/parser/ParserUtils.java
- src/main/java/seedu/splitlah/parser/commandparser/SessionCreateCommandParser.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/test/java/seedu/splitlah/command/SessionCreateCommandTest.java
- src/test/java/seedu/splitlah/parser/commandparser/SessionCreateCommandParserTest.java
> Integrate SessionCreateCommand with CommandParser

- docs/UserGuide.md
> Amend user guide with peer review suggestions

- docs/UserGuide.md
Make the introduction more user-centric and emphasize the benefits of
SplitLah to the user.
Fixes #348
> Rewrite UG intro and value proposition

- src/test/java/seedu/splitlah/data/ProfileTest.java
Added more test cases to test group related functions
Update existing assert statements
Update existing test cases to not use BeforeEach
> Added more test cases for Profile class

- .gitignore
- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/test/java/seedu/splitlah/data/SessionTest.java
Fixes #357 
Fixes #358 
Fixes #359
> Update Session class and add JUnit tests for Session class

- src/main/java/seedu/splitlah/command/SessionDeleteCommand.java
- src/main/java/seedu/splitlah/command/SessionEditCommand.java
- src/main/java/seedu/splitlah/data/Name.java
- src/main/java/seedu/splitlah/data/PersonList.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/parser/ParserUtils.java
- src/main/java/seedu/splitlah/parser/commandparser/SessionEditCommandParser.java
- src/main/java/seedu/splitlah/parser/commandparser/SessionViewCommandParser.java
- src/main/java/seedu/splitlah/ui/Message.java
> Command session edit

- src/main/java/seedu/splitlah/data/Session.java
- text-ui-test/EXPECTED.TXT
Update ordering of fields within toString method
Integrate TableFormatter into getActivityListSummaryString method
Update text-ui test file to match updates
> Integrate TableFormatter class into Session class

- src/main/java/seedu/splitlah/data/Session.java
- src/test/java/seedu/splitlah/data/SessionTest.java
Update visibility and add sorting to certain methods in Session class to support ActivityListCommand.
Add JUnit tests for hasActivity method in Session class
> Update Session class and SessionTest class

- docs/UserGuide.md
- src/test/java/seedu/splitlah/command/ActivityEditCommandTest.java
Adds SessionViewCommand to the user guide.
Fixes #379
> Add SessionViewCommand to UG

- src/main/java/seedu/splitlah/command/SessionCreateCommand.java
- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/command/SessionViewCommand.java
- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/test/java/seedu/splitlah/data/SessionTest.java
Add minor consistency fixes to other classes
Add JUnit tests for String returning methods in Session class
Add Logging and assertions to Session class
Fixes #254
> Add more JUnit tests to Session class

- README.md
- src/main/java/seedu/splitlah/parser/Parser.java
- src/main/java/seedu/splitlah/parser/ParserErrors.java
- src/main/java/seedu/splitlah/parser/ParserUtils.java
- src/main/java/seedu/splitlah/ui/Message.java
- src/main/java/seedu/splitlah/ui/TextUI.java
- text-ui-test/EXPECTED.TXT
Update welcome message to use correct casing of SplitLah
Add JavaDoc comment to ParserUtils and ParserErrors class
Add logging to Parser class
Fixes #229
> Minor additions to Parser class

- src/main/java/seedu/splitlah/command/SessionSummaryCommand.java
- src/main/java/seedu/splitlah/data/Session.java
- src/main/java/seedu/splitlah/parser/ParserErrors.java
- src/main/java/seedu/splitlah/parser/ParserUtils.java
- src/test/java/seedu/splitlah/command/GroupCreateCommandTest.java
Update JavaDoc comments to be more meaningful
Remove redundant JavaDoc comments
Extract method to ensure single responsibility of method
Fixes #442
> Update code as per suggestions from TA

- docs/team/ivan.md
> Add Project Portfolio Page

- src/main/java/seedu/splitlah/parser/ParserErrors.java
- src/test/java/seedu/splitlah/data/SessionTest.java
- src/test/java/seedu/splitlah/parser/ParserTest.java
Also update documentation to be less redundant, and remove redundant declarations
> Minor update to JUnit tests of Parser class

- src/main/java/seedu/splitlah/data/Manager.java
- src/main/java/seedu/splitlah/data/Profile.java
- src/main/java/seedu/splitlah/parser/commandparser/SessionEditCommandParser.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
> Branch bugfix and testing

- docs/DeveloperGuide.md
> Docs developerguide

- docs/DeveloperGuide.md
- docs/UserGuide.md
Add test cases for developer guide instructions for manual testing
Add warnings, instructions and specification clarification into user guide
> Update user guide and developer guide
